@host = http://localhost:4004

// Run the calls sequentially to avoid any conflicts

### Get list of all incidents
# @name incidents
GET {{host}}/odata/v4/processor/Incidents
Authorization: Basic alice:wonderland

### Getting list of attachments for a particular incidents
@incidentsID = {{incidents.response.body.value[2].ID}}
# @name attachments
GET {{host}}/odata/v4/processor/Incidents(ID={{incidentsID}})/attachments
Authorization: Basic alice:wonderland

### getting attachments content without draft mode
@attachmentsID = {{attachments.response.body.value[1].ID}}
GET {{host}}/odata/v4/processor/Incidents({{incidentsID}})/attachments(up__ID={{incidentsID}},ID={{attachmentsID}})/content
Authorization: Basic alice:wonderland

### deleting attachments content without draft mode, do not forget to replace the ID of the attachment
DELETE {{host}}/odata/v4/processor/Incidents({{incidentsID}})/attachments(up__ID={{incidentsID}},ID={{attachmentsID}})
Authorization: Basic alice:wonderland

### creating attachments content with non draft mode for a particular incident
# @name createAttachment
POST {{host}}/odata/v4/processor/Incidents({{incidentsID}})/attachments
Authorization: Basic alice:wonderland
Content-Type: application/json

{
        "filename": "sample-1.jpg"
}

### Putting content in the attachment
@attachmentsID2 = {{createAttachment.response.body.ID}}
PUT {{host}}/odata/v4/processor/Incidents({{incidentsID}})/attachments(up__ID={{incidentsID}},ID={{attachmentsID2}})/content
Authorization: Basic alice:wonderland
Content-Type: image/jpeg

< ./integration/content/sample-1.jpg

### fetching newly created attachment content
GET {{host}}/odata/v4/processor/Incidents({{incidentsID}})/attachments(up__ID={{incidentsID}},ID={{attachmentsID2}})/content
Authorization: Basic alice:wonderland
